#!/usr/bin/env bash
# THis uses scp to transfer files to a remote server
if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -eq 3 ]; then
	scp -o StrictHostKeyChecking=no $4 $1 "$3@$2:/home/$3"
else
	scp -i $4 -o StrictHostKeyChecking=no $1 "$3@$2:/home/$3"
fi
