#!/bin/bash
sudo apt-get -y update
sudo apt-get -y install nginx
sudo apt-get -y install nginx-extras
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/2022phyro permanent;/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sudo sed -i '/redirect_me https:\/\/github.com\/2022phyro/i \\terror_page 404 /error404.html;\n\tlocation = /error404.html {\n\t\troot /var/www/html;\n\t\tinternal\n\t}\n' /etc/nginx/sites-enabled/default
target=$(cat /etc/hosts | grep 127.0.0.1 | cut -d ' ' -f 3)
sudo sed -i "/^\t\ttry_files \$uri \$uri\/ =404;$/i  \\\t\tadd_header X-Served-By $target;" /etc/nginx/sites-enabled/default
sudo service nginx restart
