#!/usr/bin/env bash
#This configures an ubuntu server to install and config nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/2022phyro permanent;/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sudo sed -i '/redirect_me https:\/\/github.com\/2022phyro/i \\terror_page 404 /error404.html;\n\tlocation = /error404.html {\n\t\troot /var/www/html;\n\t\tinternal\n\t}\n' /etc/nginx/sites-enabled/default
sudo sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
