#!/usr/bin/env bash
#This script installs and configures HAproxy for ubuntu
sudo apt -y update
sudo apt -y install haproxy
echo -e "\nfrontend web_front\n\tbind *:80\n\tdefault_backend web_servers\n" >> /etc/haproxy/haproxy.cfg
echo -e "backend web_servers\n\t balance roundrobin\n\tserver 138528-web-01 100.25.17.233:80 check\n\tserver 138528-web-02 3.84.238.62:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
