#!/usr/bin/env bash
# This debugs this container and allow it listen at 80
sudo sed -i "s/listen 8080/listen 80/" /etc/nginx/sites-enabled/default
sudo sed -i "s/listen \[\:\:\]\:8080/listen \[\:\:\]\:80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
