#!/usr/bin/env bash
#Prints To infinity and beyond with a wait time of 2 seconds
touch /test/run/myscript.id
echo $$ > /test/run/myscript.id
trap 'echo "I hate the kill command"; rm -rf"/var/run/myscript.id "; exit"'SIGTERM
trap "echo 'Y U no love me?' ;" SIGINT
trap "rm -rf /var/run/myscript.id ; exit" SIGQUIT
while true
do
	echo "To infinity and beyond"
	sleep 2
done

