#!/usr/bin/env bash
#This script is displaying "Best School" 10 times
#Using while loop at the 9th iteration, print hi
x=1
while [ "$x" -le "10" ]
do
	echo "Best School"
	if [ "$x" -eq "9" ]
	then
		echo "Hi"
	fi
	x=$((x + 1))
done
