#!/usr/bin/env bash
#This script is displaying "Best School" 10 times
#Using while loop
#At the 4th iteration print bad luck from China
#at 9th iteraton print bad luck from Japan
# at 17 print bad luck from italy
# else print the numbers
x=1
while [ "$x" -le "20" ]
do
	case $x in 
		4)
			echo "$x"
			echo "bad luck from China"
			;;
		9)
			echo "$x"
			echo "bad luck from Japan"
			;;
		17)
			echo "$x"
			echo "bad luck from Italy"
			;;
		*)
			echo "$x"
	esac	
	x=$(($x + 1))
done
